Repository rancher/gke-operator, pull requests merged in 2024-10, with the labels that each got.

#672 [v2.8] fix: Update e2e k8s version
  test/e2e/templates/basic-cluster.yaml
Labels: area/ci

#671 [v2.9] fix: Update e2e k8s version
  test/e2e/templates/basic-cluster.yaml
Labels: area/ci

#673 [v1.31] Bump k8s dependencies to support k8s v1.31
  go.mod
  go.sum
Labels: kind/enhancement

#680 [v2.7] Bump image version
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .trivyignore
  package/Dockerfile
Labels: area/release, area/ci

#685 ci: Use Go 1.23 to build binary
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .trivyignore
Labels: area/ci
