Repository rancher/gke-operator, pull requests merged in 2024-01, with the labels that each got.

#256 ✨ Introduce E2E setup and tests in GKE
  .github/workflows/e2e-latest-rancher.yaml
  .github/workflows/e2e.yaml
  .github/workflows/update-rancher-charts.yaml
  .github/workflows/update-rancher-dep.yaml
  .gitignore
  Makefile
  README.md
  go.mod
  go.sum
  scripts/setup-kind-cluster.sh
  test/e2e/Dockerfile.e2e
  test/e2e/basic_cluster_test.go
  test/e2e/config/config.go
  test/e2e/config/config.yaml
  test/e2e/deploy_operator_test.go
  test/e2e/suite_test.go
  test/e2e/templates/basic-cluster.yaml
Labels: kind/enhancement

#263 Fix e2e daily tests
  .github/workflows/e2e-latest-rancher.yaml
  .github/workflows/e2e.yaml
  README.md
  test/e2e/config/config.go
  test/e2e/suite_test.go
  test/e2e/templates/basic-cluster.yaml
Labels: kind/bug, area/testing

#267 Bump Wrangler version to v2.0.2
  controller/gke-cluster-config-handler.go
  go.mod
  go.sum
  main.go
  pkg/codegen/cleanup/main.go
  pkg/codegen/main.go
  pkg/generated/controllers/core/factory.go
  pkg/generated/controllers/core/v1/interface.go
  pkg/generated/controllers/core/v1/node.go
  pkg/generated/controllers/core/v1/pod.go
  pkg/generated/controllers/core/v1/secret.go
  pkg/generated/controllers/gke.cattle.io/factory.go
  pkg/generated/controllers/gke.cattle.io/v1/gkeclusterconfig.go
  pkg/generated/controllers/gke.cattle.io/v1/interface.go
Labels: kind/chore, area/wrangler
